// Authorization
const SET_AUTH = 'SET_AUTH';
const DELETE_AUTH = 'DELETE_AUTH';

// Creator
const SET_CREATORS = 'SET_CREATORS';
const UPDATE_CREATOR = 'UPDATE_CREATOR';
const DELETE_CREATOR = 'DELETE_CREATOR';

// Business
const SET_BUSINESS = 'SET_BUSINESS';
const UPDATE_BUSINESS = 'UPDATE_BUSINESS';
const DELETE_BUSINESS = 'DELETE_BUSINESS';

export {
    SET_AUTH,
    DELETE_AUTH,
    SET_CREATORS,
    UPDATE_CREATOR,
    DELETE_CREATOR,
    SET_BUSINESS,
    UPDATE_BUSINESS,
    DELETE_BUSINESS,
};
