// Authorization
const SET_AUTH = 'SET_AUTH';
const ADD_TO_AUTH = 'ADD_TO_AUTH';
const DELETE_AUTH = 'DELETE_AUTH';

// Creator
const SET_CREATORS = 'SET_CREATORS';
const UPDATE_CREATOR = 'UPDATE_CREATOR';
const DELETE_CREATOR = 'DELETE_CREATOR';

// Business
const SET_BUSINESS = 'SET_BUSINESS';
const UPDATE_BUSINESS = 'UPDATE_BUSINESS';
const DELETE_BUSINESS = 'DELETE_BUSINESS';

// Collection
const SET_COLLECTIONS = 'SET_COLLECTIONS';
const ADD_COLLECTION = 'ADD_COLLECTION';
const DELETE_COLLECTION = 'DELETE_COLLECTION';

const SET_KEYWORDS = 'SET_KEYWORDS';

const SET_SELECTED = 'SET_SELECTED';
const ADD_SELECTED = 'ADD_SELECTED';
const REMOVE_SELECTED = 'REMOVE_SELECTED';

export {
  SET_AUTH,
  ADD_TO_AUTH,
  DELETE_AUTH,
  SET_CREATORS,
  UPDATE_CREATOR,
  DELETE_CREATOR,
  SET_BUSINESS,
  UPDATE_BUSINESS,
  DELETE_BUSINESS,
  SET_COLLECTIONS,
  ADD_COLLECTION,
  DELETE_COLLECTION,
  SET_KEYWORDS,
  SET_SELECTED,
  ADD_SELECTED,
  REMOVE_SELECTED
};
