import { createGlobalStyle } from "styled-components";

export default createGlobalStyle`
/* Generated by boilerplate */

body{
    font-family: TitlingGothicFB Normal, Work Sans;
    display: grid;
    max-width: 100%;
    overflow-x: hidden;
    grid-template-areas: "nav nav"
                        "main main"
                        ". foot";
    grid-template-rows: 50px 1fr 30px;
  };

  `;
